Nosto/nosto-php-sdk

CHANGELOG.md
composer.json

Closes #157 
#157 
The fixed and locked phpdotenv dependency (2.4.0) was clashing with Magento 2.3 higher constraint (2.5.1), preventing Nosto extension to be installed via composer in some setups.
This Dev branch was required from Magento and 2.5.1 was installed as expected

Hotfix/phpdotenv magento2.3

---

CHANGELOG.md
src/Helper/OAuthHelper.php
src/Operation/OAuth/AuthorizationCode.php
tests/unit/Helper/OAuthHelperTest.php

Fixes double oauth redirect url issue. Closes #172

Fix double encoding for oauth redirect URLs 

---

src/Helper/HtmlMarkupSerializationHelper.php

Check the $object variable for floating zero value, else it does return an empty string while serializing the HTML tag. 
closes #175
It was observed that in Magento2, products that had price zero were not serialized as they should, skipping the price tag.

Add check for floating zero

---

CHANGELOG.md
src/Helper/UrlHelper.php
src/Operation/AbstractAuthenticatedOperation.php
src/Operation/AbstractOperation.php
src/Operation/DeleteProduct.php
src/Operation/InitiateSso.php
src/Operation/MarketingPermission.php
src/Operation/OrderConfirm.php
src/Operation/Recommendation/AbstractOperation.php
src/Operation/SyncRates.php
src/Operation/UpdateSettings.php
src/Operation/UpsertProduct.php
src/Request/Http/HttpRequest.php
tests/unit/HttpRequestTest.php
tests/unit/Operation/ProductTest.php

closes #182 #131   
* Add possibility to define active domain and Nosto account for API calls and HTTP requests in general
#182 
#131 
We check on Nosto's end that the active domain is in the allowed domains. This will also help us debug API related issues. 
* ToDo - add some tests

Add possibility to define Nosto account & active domain for API calls

---

src/Helper/ArrayHelper.php
src/Helper/HtmlMarkupSerializationHelper.php
src/Helper/SerializationHelper.php
tests/unit/Helper/ArrayHelperTest.php

* Add `ArrayHelper` class.
* Add method to check if an array contains only scalar values
* Migrate `SerializationHelper::isAssoc` and `SerializationHelper::stdClassToArray` to ArrayHelper
closes #190
Created unit test.

Add method to check if array contains only scalable values

---

src/Helper/HtmlMarkupSerializationHelper.php
src/Mixins/HtmlEncoderTrait.php
src/Object/Signup/Signup.php

* Add the `APPS` token to the list of tokens that are generated automatically on creating new Nosto account
* Refactor: renamed `HtmlMarkupSerializationHelper::canEncoded` to `HtmlMarkupSerializationHelper::canBeEncoded` 
closes #191 #192
The `APPS` token was not generated when creating new account
Manually.

Add APPS token to the default tokens when creating Nosto Account

---

CHANGELOG.md
src/Helper/IframeHelper.php
src/Mixins/IframeTrait.php
src/bootstrap.php
tests/_bootstrap.php

Use reflection to support both vlucas/phpdotenv versions 2.x and 3.x
Fixes #208 
Shopware is now using the version 3.x of phpdotenv dependency, whereas Magento 2 is still using version 2.6. This makes the dependency compatible with both versions
Deployed to Plugintest with Shopware, the invalid constructor argument error is now fixed.

Feature - Use reflection to support both vlucas/phpdotenv versions 2.x and 3.x

---

CHANGELOG.md
src/Object/Product/Sku.php
tests/_support/MockSku.php
tests/unit/Helper/SerializationHelperTest.php

Amend inventory level on SKU products as well.
Closes #174 
We already had the field available on Playcart, but the extensions are not sending the SKU level. This makes it available for the extensions to send this extra field.
Tested with Magento 1 extension. See [this PR](https://github.com/Nosto/nosto-magento/pull/525).
N/A

Feature/add inventory level SKU

---

CHANGELOG.md
src/Helper/ArrayHelper.php
src/Helper/SerializationHelper.php
tests/unit/Helper/SerializationHelperTest.php

Sort attributes when serializing an object.
#241 
When comparing two serialized objects the order of the attributes should not matter. 
Added a test for comparing objects.

Sort array by keys when serializing object to json

---

CHANGELOG.md
src/Operation/Order/OrderCreate.php
src/Types/Order/OrderInterface.php

Add a null check for the order confirmation API call variables. 
#250
Order confirmation throws a fatal error if customer is null.
Tested with Magento 2 by forcing the customer to be null.

Add a null check for the customer object in order confirmation

---

CHANGELOG.md
src/Operation/Recommendation/CategoryMerchandising.php

Add skipVCEvent to the graphql query in order not to create a VC event when making the query.

Add skipVCEvent to the query

---

CHANGELOG.md
composer.json
composer.lock

Prestashop ps_checkout module uses dotenv 3.4, which conflicts with our SDK dotenv version, making it impossible to run both modules alongside. This PR bumps the max version for the dotenv dependency
Tested with Prestashop 1.7 and PS_checkout 1.5.2

Upgrade vlucas/dotenv to 3.6

---

CHANGELOG.md
src/.env
src/Result/Graphql/Recommendation/RecommendationResultHandler.php
tests/unit/Result/GraphqlCMPTest.php

Handle gracefully recommendation responses that don't have result id in response.
#278 
We should not throw an exception for a normal response. If there are no results (for example for CMP) it's not a error but most likely a category that has not been configured to have CMP. 
* Added a unit test
* Tested locally with M2 CMP

Fix the recommendation result set parsing when resultId is not present

---

PHP-SDK.iml
src/Operation/Recommendation/AbstractRecommendation.php
src/Operation/Recommendation/BatchedCategoryMerchandising.php
src/Util/Recommendation.php

Introduce new service / operation for batching the CMP calls to around the limitation of max 250 products. 
#286 
On some category pages all products in a category can be viewed and we must be able to return all products in the category from Nosto.  
Tested locally with several limits.

Support batched category merchandising calls 

---

src/Operation/Recommendation/CategoryMerchandising.php
src/Result/Graphql/Recommendation/CategoryMerchandisingResult.php
src/Result/Graphql/Recommendation/RecommendationResultHandler.php
src/Util/Recommendation.php
tests/unit/Result/GraphqlCMPTest.php

The time of response of the GraphQl call will increase when paginating. To overcome this issue, the batchToken that is return from the current page, can be passed to the next call. 
In this change, a method to add batchTokeb to the `CategoryMerchandising` object.

Add batchToken to GraphQl

---

src/Operation/Recommendation/BatchedCategoryMerchandising.php
src/Util/Recommendation.php

The batch token is added to the batched CMP calls. 
Batch token speeds up the fetching the CMP results in Nosto's end.  
Tested locally

Add batch token to batched CMP calls

---

.github/workflows/action.yml
.github/workflows/ide.yml
.github/workflows/phan.yml
.github/workflows/tests.yml
CHANGELOG.md
src/Util/HttpResponseException.php

When trying to parse the exception message, the function check if the response type is exactly `application/json`, but it might also contain the utf chatset in the same string. As a result the response message will not be logged. Fix the issue by checking if it contains the string instead.

Check if the response content type contains application/json

---

CHANGELOG.md
src/Result/Graphql/Recommendation/RecommendationResultHandler.php

When batchToken value is null an exception is thrown by the SDK, and the CMP results are not displayed

Hotfix 5.3.5 - Fix CMP failing when batchToken value is null

---

CHANGELOG.md
src/Result/Graphql/Recommendation/RecommendationResultHandler.php

When batchToken value is null an exception is thrown by the SDK, and the CMP results are not displayed

Hotfix 5.3.5 - Fix CMP failing when batchToken value is null 

---

CHANGELOG.md
src/Model/Product/Product.php
src/Model/Product/Sku.php
src/Model/Product/Variation.php

Floating numbers have a maximum precision of 14 digits. When the price exceeds this precision there is a discrepancy between the price value that comes through API (it will be a string and have the correct value) and the one tagged in the product page (will be rounded). 
To fix this, round the price to 2 decimal places.

Limit the price float value to 2 decimal places

---

.github/workflows/action.yml
.github/workflows/ide.yml
.github/workflows/phan.yml
.github/workflows/tests.yml
CHANGELOG.md
composer.json
composer.lock
src/Helper/ExportHelper.php
src/Request/Http/Exception/AbstractHttpException.php

Magento 2.4.4 requires `phpseclib v3` but M2 2.4.3 requires `phpseclib v2`.

Add compatibility for different phpseclib versions

---

src/Request/Http/HttpRequest.php

Restore replaceQueryParamsInUrl that was deleted during Magento 2 iframe removal release.

Restore replaceQueryParamsInUrl function

---

composer.json
composer.lock
src/Helper/AbstractExportHelper.php
src/Helper/ExportHelper.php
tests/unit/HistoryExportTest.php

Use gcm for encryption

---

tests/unit/HttpRequestTest.php

The reason this test fails is the error response string slightly change over different curl versions.

Loosen assertion curl response test message
