Nosto/nosto-php-sdk

src/classes/export/NostoExportProductCollection.php
src/classes/operation/NostoOperationProduct.php
src/interfaces/NostoProductInterface.php

Add new product fields to SDK and unify the usage of product serializer

---

src/classes/helper/NostoHelperIframe.php
src/interfaces/account/NostoAccountMetaDataIframeInterface.php
tests/_support/NostoAccountMetaDataIframe.php

Add traffic data to iframe url

Add traffic data to iframe url

---

src/Request/Http/Adapter/Adapter.php
src/Request/Http/Exception/AbstractHttpException.php
src/Request/Http/HttpResponse.php

Add support for getting x request on http response and http exception

---

composer.json
composer.lock
src/Object/Product/VariationCollection.php

This makes serializer to treat collection as an associative array

Add array key for price variation collection

---

src/Object/Product/Product.php
src/Object/Product/Sku.php

Support custom fields in product

Add custom fields to product class

---

src/Operation/AccountSignup.php
src/Request/Http/Adapter/Adapter.php
src/Request/Http/Adapter/Curl.php
src/Request/Http/Adapter/Socket.php
src/Request/Http/HttpRequest.php

Increase timeout for account creation

---

src/Helper/IframeHelper.php
src/Helper/OAuthHelper.php
src/Mixins/IframeTrait.php
src/Nosto.php
src/Operation/OAuth/AuthorizationCode.php
src/Request/Api/ApiRequest.php
src/Request/Http/HttpRequest.php
tests/unit/HttpRequestTest.php
tests/unit/IFrame/IframeAuthTest.php

Add methods to get env variables directly

---

src/Helper/HtmlMarkupSerializationHelper.php
src/Request/Http/HttpRequest.php

Add notranslate tag to avoid tagging being translated by browser plugin

---

CHANGELOG.md
Dockerfile
composer.json
composer.lock
ruleset.xml
src/Object/Order/Order.php

Remove DateTimeInterface and add PHP version compatibility check

---

CHANGELOG.md
src/Object/Product/Product.php

Change product tag1, tag2 and tag3 tagging to tags1, tags2 and tags3

Hotfix 3.1.3

---

CHANGELOG.md
src/Object/Cart/Cart.php

Rename Cart::restoreCartUrl to Cart::restoreLink for supporting html serializer

Hotfix 3.1.4

---

src/Helper/AbstractExportHelper.php
src/Helper/ExportHelper.php
tests/unit/HistoryExportTest.php

Remove static abstract functions because it is not allow in php strict mode

hotfix 3.1.6

---

CHANGELOG.md
src/Helper/HtmlMarkupSerializationHelper.php
tests/_support/MockProductWithSku.php
tests/unit/Helper/HtmlMarkupSerializationHelperTest.php
tests/unit/Helper/SerializationHelperTest.php

Fix the issue that custom field keys were converted to snake case
Closes #113

Hotfix 3.2.1

---

CHANGELOG.md
src/Object/MarkupableString.php

Hotfix 3.4.2

---

src/Operation/MarketingPermission.php
tests/api-blueprint.md
tests/unit/Operation/MarketingPermissionTest.php

Support marketing permission api operation

---

CHANGELOG.md
src/Object/Category.php

Added type  `int` to annotations

Hotfix - 3.8.1

---

src/Object/AbstractPerson.php
src/Types/PersonInterface.php
tests/_support/MockCustomer.php
tests/unit/Helper/HtmlMarkupSerializationHelperTest.php

Add new field to customer tagging

---

src/Request/Http/Adapter/Curl.php
src/Request/Http/HttpResponse.php
tests/unit/HttpResponseTest.php

Support and parses the header of the HTTP 2 response
closes #149

Add suport for http 2 responses

---

composer.json
composer.lock
src/Helper/ExportHelper.php
src/Helper/IframeHelper.php
src/Helper/PriceHelper.php
src/Helper/ValidationHelper.php
src/Object/Category.php
src/Object/Email/ImageUrl.php
src/Object/Notification.php
src/Object/Settings.php
src/Operation/AbstractOperation.php
tests/unit/Helper/HtmlMarkupSerializationHelperTest.php

Phan was deprecated and the package used has been abandoned for quite some time.
This PR upgrade Phan to latest version and fix new errors found
Closes #165 
All unit tests have passed.

Hotfix/Bump Phan Version and Vendor

---

tests/unit/IFrame/IframeAuthTest.php

Test and assert that params related to error messages are parsed correclty
close #163

Add assertion for error message params

---

tests/unit/Helper/HtmlMarkupSerializationHelperTest.php
tests/unit/Helper/SerializationHelperTest.php

Test cases when custom field key contains special characters
closes #92

Add test for special character serialization

---

Jenkinsfile
src/Exception/Builder.php
src/Nosto.php
src/Operation/AbstractOperation.php
src/Operation/InitiateSso.php
src/Operation/OAuth/AuthorizationCode.php
src/Operation/OAuth/ExchangeTokens.php
src/Operation/Recommendation/AbstractOperation.php
tests/unit/NostoTest.php

Refactor the error throwing logic, so the error is thrown from the class that causes it 
closes #138

Refactor error throwing in PHP SDK

---

src/Exception/MemoryOutOfBoundsException.php
src/Exception/OutOfMemoryException.php
src/Operation/UpsertProduct.php
src/Util/Memory.php

- Add memory utility class to SDK.
- Implement Clear Upsert Collection method to lower memory consumption
- Add OutOfMemory exception type
Closes #185
We need to profile and assure that certain features of our plugins do not eat up too much memory. This class will make it easier to measure the consumption.
This has been tested manually with Nosto Magento 2 plugin.

Add Memory Util & Clear Upsert Collection

---

src/Object/Product/Product.php

Added constants to hold product tags values in order to avoid typos.
closes #186

Add tags values as constants

---

Dockerfile

Old image is no longer updated from backports repository e was causing some packages to not be found.
Fixes #200
Image built locally

Bump dockerfile PHP image

---

CHANGELOG.md
composer.json
composer.lock
src/bootstrap.php
tests/_bootstrap.php

Reverts Nosto/nosto-php-sdk#206
This will cause issues with Magento 2

Revert "Feature - Bump dotenv dependency"

---

CHANGELOG.md
src/Object/Product/Sku.php
tests/_support/MockSku.php
tests/unit/Helper/SerializationHelperTest.php

Release 3.15.0 - Add inventory level to SKU.
N/A

Release/3.15.0 - Add inventory level to SKU

---

CHANGELOG.md
src/Operation/Recommendation/CategoryMerchandising.php

Fixes wrong value being set to preview mode on CMP GraphQL Query
Closes #228 
Wrong Value being sent to playcart
Checked with the debugger and playcart payload
N/A

Fix preview mode query var

---

CHANGELOG.md
src/Operation/Recommendation/CategoryMerchandising.php

Update CMP GraphQL query to use category name as recommendation parameter

Update CMP GraphQL Query

---

src/Operation/Recommendation/AbstractFilters.php
src/Operation/Recommendation/CategoryMerchandising.php
src/Operation/Recommendation/ExcludeFilters.php
src/Operation/Recommendation/Filters.php
src/Operation/Recommendation/IncludeFilters.php

Enable the usage of facets to query products. 
closes #240

Implement faceting to cmp query

---

CHANGELOG.md
src/Exception/FilteredProductException.php
src/Exception/NonBuildableProductException.php

Introduce two new exception types
We need exceptions to indicate why product building might have failed.  
* Not used internally in SDK at the moment. Nothing to test.

Introduce new exception types for product building failures

---

src/Operation/Recommendation/CategoryMerchandising.php

Remove VP event from query by using session query instead
closes #248

Remove the VP event

---

CHANGELOG.md
composer.json
composer.lock
src/Request/Http/Exception/AbstractHttpException.php
src/bootstrap.php

Update outdated composer dependencies.
Fixes #254
N/A

Hotfix 4.0.8 - Update Dependencies

---

composer.json
composer.lock

Remove symfony/console unused dependency

---

CHANGELOG.md
src/Result/Graphql/Order/OrderCreateResultHandler.php
src/Result/Graphql/Order/OrderStatusResultHandler.php

Remove exception that was being thrown from playcart, causing merchants to raise tickets

Remove OrderCreate GraphQL No Place Order found exception

---

CHANGELOG.md
composer.json
composer.lock

The composer lock was causing trouble when installing with PHP < 7.2

Hotfix 4.0.10 - Update lock

---

src/Exception/TokenException/MissingAppsTokenException.php
src/Result/Graphql/Recommendation/RecommendationResultHandler.php

Add exception class for Missing API_APPS token
closes #261

Add new exception class

---

composer.json
composer.lock

Upgrade our Phan runner
Our Phan was too outdated and many new features couldn't be used.
Also, no need to downgrade your AST extension version when using it.
Tests pass.
N/A

Upgrade Phan to 2.*

---

src/Model/Format.php
src/Util/Serialize.php

Introduce utility for serialising and deserialising objects
Serialising is needed when for example caching objects on platform side.

Introduce util for serialising and deserialising objects

---

CHANGELOG.md
src/Operation/Recommendation/BatchedCategoryMerchandising.php

Add support for defining the batch token when initialising batched CMP operation. 
This is needed when pagination is used on a platform side. 
#291
Tested locally

Add support for initial batch token in batched CMP operation

---

CHANGELOG.md
src/Operation/Recommendation/BatchedCategoryMerchandising.php

Master to develop (5.3.1)

---

CHANGELOG.md
src/Operation/Recommendation/BatchedCategoryMerchandising.php
src/Operation/Recommendation/BatchedCategoryMerchandisingInterface.php
src/Operation/Recommendation/CategoryMerchandisingInterface.php

The CMP module makes use of observer events to alter the query class by adding the batch token.
Added methods:
`setBatchToken`
`getLimit`
`getSkipPages`

Intorduce interface to handle parameters for batched cm requests

---

CHANGELOG.md
src/Operation/Recommendation/BatchedCategoryMerchandising.php

The value passed for skipPages is incorrect. It always starts from 0.

Pass the correct skipPages value

---

CHANGELOG.md
src/Result/Graphql/Recommendation/RecommendationResultHandler.php

Reverts Nosto/nosto-php-sdk#298

Revert "Hotfix 5.3.5 - Fix CMP failing when batchToken value is null"

---

src/Operation/AbstractGraphQLOperation.php
src/Operation/AbstractOperation.php
src/Operation/CartOperation.php
src/Operation/UninstallAccount.php
src/Request/Http/HttpRequest.php

Pass the merchant id as a query parameter merchant-id

Pass merchant id as query parameter

---

package-lock.json
package.json

Upgrade js dependencies

---

CHANGELOG.md
package-lock.json
package.json
src/Operation/AbstractGraphQLOperation.php
src/Operation/AbstractOperation.php
src/Operation/CartOperation.php
src/Operation/UninstallAccount.php

Release - 5.3.6

---

package.json

Upgrade grunt version to >=1.3.0

Upgrade grunt version

---

package-lock.json

Update path-parse to a non-vulnerable version
Dependabot alert

Upgrade path-parse dependency

---

.github/workflows/codeql-analysis.yml
.idea/inspectionProfiles/CI.xml
.idea/php.xml
src/Operation/Session/NewSession.php
src/Result/Graphql/GraphQLResultHandler.php
src/Result/Graphql/Recommendation/RecommendationResultHandler.php
src/Result/Graphql/Session/SessionResultHandler.php

Create new operation class to handle the creation of a new session. The query must have the option to force the session not to be tracked. 
This requirement comes from CM: https://github.com/Nosto/nosto-magento2-cmp/pull/110

Implement newSession query in the client

---

.github/workflows/ide.yml
CHANGELOG.md
inspect.sh
src/Exception/NonBuildableProductException.php

Improve NonBuildableProductException by passing the previous exception. This will make debugging easier by looking at the previous stacktrace.

Hotfix - 5.4.1

---

composer.json
composer.lock

Upgrade dotenv

---

composer.json
composer.lock
src/Helper/ExportHelper.php
tests/unit/HistoryExportTest.php

Bump phpsec lib

---

CHANGELOG.md
src/Model/AbstractCollection.php

Suppress inheritance warning for PHP 8.1

---

src/Helper/ConnectionHelper.php
src/Model/ConnectionMetadata.php
src/Types/ConnectionMetadataInterface.php
tests/_support/MockConnectionMetadata.php
tests/unit/Connection/ConnectionAuthTest.php

Remove unique installation id that is not in use anymore

Remove unique installation id

---

src/Model/Product/Product.php
src/Types/Product/ProductInterface.php

Add category ids to Product model

---

.github/workflows/ide.yml

PHPStorm inspection 2023.1.2

---

src/Operation/Search/SearchOperation.php

When providing an empty array to the rules parameter, the rules for CM2 are not considered. Additionally, I made the file PHP 5.5 compatible.

Fix category merchandising

---

src/Util/HttpResponseException.php

Add message when getting empty responses from API

---

src/Operation/Search/SearchOperation.php

SSP-24 Request custom fields for search request

---

src/Operation/AbstractOperation.php
src/Request/Http/Adapter/Adapter.php
src/Request/Http/HttpRequest.php

Change timeout values

---

.github/workflows/action.yml
.github/workflows/ide.yml
.github/workflows/phan.yml
.github/workflows/tests.yml

Bump actions/upload-artifact to v4

---

src/Request/Graphql/SearchRequest.php

SSP-173 Add a timeout to Search API Request

---

.github/workflows/action.yml
.github/workflows/ide.yml
.github/workflows/phan.yml
.github/workflows/tests.yml
composer.json
src/.env
src/Model/Analytics/AnalyticsCategoryMetadata.php
src/Model/Analytics/AnalyticsSearchMetadata.php
src/Model/Analytics/DataSource.php
src/Nosto.php
src/Operation/AbstractOperation.php
src/Operation/AbstractSearchOperation.php
src/Operation/Category/AnalyticsCategoryTracking.php
src/Operation/Search/AnalyticsSearchTracking.php
src/Request/Api/SearchAnalyticsRequest.php
src/Request/Graphql/SearchRequest.php
src/Request/Http/HttpRequest.php
tests/unit/HttpRequestTest.php

Release 7.6.1

---

composer.json

Bump Version to 7.6.1

---

composer.json

Bump Version to 7.6.2

---

src/Helper/SerializationHelper.php

Needed for snake case based tagging providers

Serialization Helper to Array Public

---

.github/workflows/action.yml
.github/workflows/ide.yml
.github/workflows/phan.yml
.github/workflows/tests.yml
CHANGELOG.md

There is a discrepancy between the changelog file and our releases in github. 
This PR fixes it for future references and releases

Fix version discrepancy

---

src/Operation/Category/CategoryUpdate.php
src/Types/CategoryInterface.php

Add the url to upsertCategories mutation

Send category url to Nosto

---

src/Operation/Search/SearchOperation.php
src/Request/Http/HttpRequest.php

NS-11350 Change empty string for query to null

---

CHANGELOG.md
composer.json

Release 7.6.6

---

src/Exception/NonBuildableProductException.php
src/Helper/ConnectionHelper.php
src/Operation/AbstractOperation.php
src/Operation/AbstractSearchOperation.php
src/Request/Http/Exception/AbstractHttpException.php
src/Request/Http/HttpRequest.php

Make code campatble with new php versions
